wandb_version: 1

config_file:
  value: ./configs/small.json
cooldown_proportion:
  value: 0.09360381341875472
ema_decay:
  value: 0.999
global_batch_size:
  value: 256
hybrid_denominator:
  value: 4
hybrid_numerator:
  value: 2
learning_rate:
  value: 0.0013706777309009583
local_batch_size:
  value: 16
mask_keep_p:
  value: 0.18365480979833432
mask_p_end:
  value: 0.1281937039809573
mask_p_start:
  value: 0.21035202099644612
mask_random_p:
  value: 0.17133263682491565
mixed_precision:
  value: true
name:
  value: hybrid_mlm_clm_10M
optimizer:
  value: lamb
output_dir:
  value: ./model_checkpoints
save_every:
  value: 5000
seed:
  value: 42
seq_length:
  value: 128
tokenizer_path:
  value: ./tokenizers/tokenizer_10M.json
train_path:
  value: ./data/train_10M_tokenized.bin
valid_path:
  value: ./data/valid_10M_tokenized.bin
validate_every:
  value: 5000
warmup_proportion:
  value: 0.04967454154985034
weight_decay:
  value: 0.00931039629619471
